# action.yml
name: 'DingTalk Message'
description: 'Send a DingTalk robot message'
inputs:
  token:  
    description: '# dingtalk robot token'
    required: true
    default: 'token'
  title:  
    description: '# message title'
    required: true
    default: 'message title'         
  type:  
    description: '# message type'
    required: false
    default: 'markdown'
  content:  
    description: '# message content'
    required: false
    default: ''    
  file:  
    description: '# message content saved in file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

  