# action.yml
name: 'DingTalk Message'
description: 'Send a DingTalk robot message'
inputs:
  corpid:  
    description: '# openplatform corpid'
    required: true
    default: 'corpid'
  corpsecret:  
    description: '# openplatform corpsecret'
    required: true
    default: 'corpsecret'
  token:  
    description: '# openplatform token'
    required: true
    default: 'token'        
  msg:  
    description: '# openplatform token'
    required: true
    default: 'Hello, World'         
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}