# action.yml
name: 'DingTalk Message'
description: 'Send a DingTalk robot message'
inputs:
  corpid:  
    description: '# openplatform corpid'
    required: true
    default: 'corpid'
  corpsecret:  
    description: '# openplatform corpsecret'
    required: true
    default: 'corpsecret'
  token:  
    description: '# openplatform token'
    required: true
    default: 'token'        
  title:  
    description: '# message title'
    required: true
    default: 'message title'
  file:  
    description: '# message content file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

  