# action.yml
name: 'DingTalk Message'
description: 'Send a DingTalk robot message'
inputs:
  token:  
    description: '# openplatform token'
    required: true
    default: 'token'
  title:  
    description: '# message title'
    required: true
    default: 'message title'         
  type:  
    description: '# type of the message'
    required: false
    default: 'markdown'
  file:  
    description: '# message content file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'

  