on: [push]

jobs:
  dingtalk-message:
    runs-on: ubuntu-latest
    name: send a dingtalk message 
    steps:
      - name: Output file
        id: output
        run: go help > test.output
      - name: Send a dingtalk robot message
        id: push
        uses: hugozhu/dingtalk-github-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          type: markdown
          title: 'Hello from Github action'
          content: |
            ## Text Content
            > from github action message          
          file: test.output