on: [push]

jobs:
  dingtalk-message:
    runs-on: ubuntu-latest
    name: send a dingtalk message 
    steps:
      - name: Send a dingtalk robot message
        id: push
        uses: hugozhu/dingtalk-github-action@v1
        with:
          corpid: ${{ secrets.CORP_ID }}
          corpsecret: ${{ secrets.CORP_SECRET }}
          token: ${{ secrets.TOKEN }}
          msg: 'Hello from Github action'